### ISSUE TITLE
GNOME 3.24.2

### ISSUE THREAD

**Issue by FireWolf74** [zpydr/gnome-shell-extension-taskbar#169]
Why can I put everything that I have in my Top Panel into my Bottom Panel?   I would really like this help and Maybe up streamed to GNOME 3.26

**Comment by lsatenstein** [comment]
Open up taskbar settings 
On the overview tab, bottom on/off, turn to on.
You can centre the bottom panel too. Its not hard to figure it out, look at second tab. top for positioning.

**Comment by FireWolf74** [comment]
I have done that and I can not get my clock, system, applications, or anything else on bottom.  I have been looking and trying different thing but it will not work

**Comment by lsatenstein** [comment]
Firewolf74, my email is my name at yahoo.com   If you are in North America, we can chat by phone.

**Comment by FireWolf74** [comment]
Would love to but I'm at work and will not be off until sometime tomorrow.

**Comment by lsatenstein** [comment]
When you say everything, do you mean  calendar, system tray etc.
There is a different extension around that seems to do that.
I just use taskbar on the bottom panel

**Comment by FireWolf74** [comment]
everything i have in my top panel i want in the bottom

**Comment by lsatenstein** [comment]
Scroll through the extensions (80 pages) and/or search for one that claims to do it.
There is a search bar with extensions.

I am most happy with just TaskBar on the bottom panel.
You can adjust TB to show open applications,  and highlight the one with the active window. So I see no benefit to me in doing what you are striving to do.

**Comment by FireWolf74** [comment]
Does it work with 3.24.2? and 3.26

**Comment by lsatenstein** [comment]
You are on git. You can download and use it. You can also browse the source code and read 
3.26 therein.

**Comment by tpoint75** [comment]
I have the same issue in ubuntu 17.10. It seems to have to do with (a resolution change during) viewing a video in fullscreen on youtube. Deactivating and activating this extension brings the taskbar back.

**Comment by lsatenstein** [comment]
Here is what I will paste to the Fedoraforum.org in two days (after go-live with Fedora 27
Just sending a note about Gnome 3.26.1
 
TaskBar@zpydr runs just fine with ext4 and xfs systems.

Given the Fedora 27 Linux is being released in two days, I thought I would discuss my experiences since the beginning of last year.
With this extension when / and /home are established onto a btrfs file system. the results were lockup during installation andlockup during use.   Gnome support blamed the extension, though the extension works flawlessly with ext4 and xfs for several yearsand several gnome versions. The experience I had also pertained to Fedora 27 and Gnome 3.26.1 and probably Manjaro and Ubuntu.

The recent weeks up to November 10, saw a very large number of glib and gnome-shell updates for Fedora 27 beta. 
I am now able, with one or two reboots, (should not have to reboot), install any extension onto a "btrfs only" system.

I discovered that if I put one critical file onto an ext4 system, I can do a clean installation of all Gnome extensions without having to reboot.
that file is

~/.config/dconf/user
Even though Fedora 27 is entirely installed onto a btrfs system (/ and /home), I found a partition with ext4. I relocated that file to the ext4 file system 
using a soft link.  That partition happens to be /boot   The  /boot is only used during a boot.

My steps were simple because, Fedora requires  /boot to be an ext4, xfs or lvm file system
As root I did the following.
1) mkdir     -p  /boot/.config/dconf
2) cp /home/leslie/.config/dconf/user        /boot/.config/dconf
3)  mv  /home/leslie/.config/dconf             /home/leslie/.config/dconf.bak  #just in case.
4) ln -s /boot/.config/dconf          home/leslie/.config/dconf   
5) chown -R leslie:leslie   /boot/.config      #my logon is leslie.
6) Log into my Leslie logon.   Success.
from ~  I when I excecute   ls -l ~/.config | grep conf  I see the following
lrwxrwxrwx.  1 root   root     19 Nov 12 17:44 dconf -> /boot/.config/dconf
drwxr-xr-x.  2 leslie leslie 4096 Nov 12 16:00 dconf.bak


Gnome 3.26.2 with btrfs may not require the above steps. 3.26.2 will probably
appear in Fedora 27 within two weeks.

My 

 Regards 
 Leslie
 Leslie Satenstein
Montréal Québec, Canada

**Comment by zpydr** [comment]
In order to have the complete top panel show on the bottom of the screen, then have a look at the bottom panel extension by abstract: https://extensions.gnome.org/extension/949/bottompanel/
TaskBar has an implementation to work on this.
