### ISSUE TITLE
Thanks so much!

### ISSUE THREAD

**Issue by saghm** [zpydr/gnome-shell-extension-taskbar#210]
Hi! I'm not sure if this is a suitable place to say this, I just saw the notice about this no longer being worked on (I'm incidentally doing a new installation today), and I just wanted to say thanks for all the hard work you've put into this over the years! I've been using this on all my machines for several years now, so I really appreciate the effort you've given for it.

Good luck with everything in the future!

**Comment by lsatenstein** [comment]
ZpydrDo you really want to see your baby die? Please restore your git file so that it can continue and flourish.  Manjaro Linux is including it as a standard extension. TaskBar has many many users and fans. Do not let them down and later, have no long lasting fond memory. 
All the best from all of us.

Sent from Yahoo Mail on Android 
 
  On Wed, 28 Nov 2018 at 5:48 PM, Saghm Rossi<notifications@github.com> wrote:   
Hi! I'm not sure if this is a suitable place to say this, I just saw the notice about this no longer being worked on (I'm incidentally doing a new installation today), and I just wanted to say thanks for all the hard work you've put into this over the years! I've been using this on all my machines for several years now, so I really appreciate the effort you've given for it.

Good luck with everything in the future!

**Comment by saghm** [comment]
Look at the README file; it literally has a link to the old code in it. Please don't spam my issue with unrelated comments.

**Comment by lsatenstein** [comment]
The old code link was not there when I read the message.  There is so and there is recognition. You and many others have enjoyed using his creation, and he deserves recognition.
Spamming is when you distribute criticism.

Sent from Yahoo Mail on Android 
 
  On Wed, 28 Nov 2018 at 6:07 PM, Saghm Rossi<notifications@github.com> wrote:   
Look at the README file; it literally has a link to the old code in it. Please don't spam my issue with unrelated comments.
