### ISSUE TITLE
Anyone hacked this to work on 3.32.0?

### ISSUE THREAD

**Issue by lonix1** [zpydr/gnome-shell-extension-taskbar#213]
Just upgraded to Ubuntu 19.10 /  gnome 3.32.0. The old hacks stopped working.

Anyone have a new workaround?

**Comment by esauloff** [comment]
@lonix1
I made it work on Fedora 30 with Gnome 3.32.2.
Used similar issue fix from Dash-to-Panel extension here:
https://github.com/home-sweet-gnome/dash-to-panel/commit/d71893e655973ac669d8e9251bb072a887afb0d6

So in `./TaskBar@zpydr/extension.js`:
```
//const RemoteMenu = imports.ui.remoteMenu;
...
this.taskMenu = new imports.ui.remoteMenu.RemoteMenu(button, app.menu, app.action_group);
```

**Comment by lonix1** [comment]
IT WORKS AGAIN! :smile: 

For everyone else, he was referring to [this line](https://github.com/zpydr/gnome-shell-extension-taskbar/blob/39b36aba2611c42cefbbf9beab60d46ce75ec82c/extension.js#L1897). After the edits, make sure to restart the gnome session - on ubuntu it's <kbd>alt+f2</kbd> and then <kbd>r</kbd>.

Frankly I don't understand why this hack works, because it's just defining the object using the full namespace instead of importing it... but it works!

**Comment by lsatenstein** [comment]
For what it is worth, this is what my TaskBar@zpydr/scripts folder hastaskbar.conf   

and a change of import.shFromif [ ! -f $HOME/taskbar.dconf ]; then
    zenity --info --text 'Import of TaskBar Settings Failed!'
else
    dconf load /org/gnome/shell/extensions/TaskBar/ <$HOME/taskbar.dconf
    killall gnome-shell-extension-prefs
    zenity --info --text 'Import of TaskBar Settings Successful!' && gnome-shell-extension-prefs TaskBar@zpydr
fi

TO
this_dconf='share/gnome-shell/extensions/TaskBar@zpydr/scripts/taskbar.dconf'

if [  -f $HOME/.local/$this_dconf ];then
   this_dconf="$HOME/.local/$this_dconf"
else
  this_dconf="/usr/$this_dconf"         #future
fi

if [ ! -f $HOME/taskbar.dconf ]; then
    if [ ! -f $this_dconf ]; then
        zenity --info --text 'Import of TaskBar Settings Failed!'
    else
         cp $this_dconf $HOME
         zenity --info --text 'taskbar.dconf imported!' && gnome-shell-extension-prefs TaskBar@zpydr
         dconf load /org/gnome/shell/extensions/TaskBar/ <$HOME/taskbar.dconf
         killall gnome-shell-extension-prefs
         zenity --info --text 'Import of TaskBar Settings Successful!' && gnome-shell-extension-prefs TaskBar@zpydr
    fi
else
     dconf load /org/gnome/shell/extensions/TaskBar/ <$HOME/taskbar.dconf
     killall gnome-shell-extension-prefs
     zenity --info --text 'Import of TaskBar Settings Successful!' && gnome-shell-extension-prefs TaskBar@zpydr
fi


This is my taskbar.dconf that I store in the scripts directory
[/]
scroll-tasks='off'
tasks-all-workspaces=true
display-favorites-label='description'
display-showapps-button=true
showapps-button-toggle='leftclickappview'
inactive-tasks-label-color='rgb(252,233,79)'
position-max-right=2
display-tasks-frame-color=true
tasks-label='app'
position-favorites=2
inactive-tasks-frame-color='rgb(239,41,41)'
bottom-panel=true
bottom-panel-original-background-color='rgba(0, 0, 0, 89)'
activities-button=true
inactive-task-frame=true
position-bottom-box=1
position-workspace-button=0
application-menu-color='rgb(138,226,52)'
first-start=false
application-menu=false
tray-button-icon='/home/leslie/.local/share/gnome-shell/extensions/TaskBar@zpydr/images/bottom-panel-tray-button.svg'
inactive-task-background-color='rgb(136,138,133)'
dash=true
display-inactive-tasks-label-color=true
activities-button-color='rgb(252,233,79)'
display-favorites=true
hover-switch-task=true
separator-right-appview=27
export-settings=false
desktop-button-icon='/home/leslie/.local/share/gnome-shell/extensions/TaskBar@zpydr/images/desktop-button-default.png'
inactive-task-background-color-set=true
position-changed=true
display-inactive-tasks-frame-color=true
tasks-label-color='rgb(138,226,52)'
extension-path='/home/leslie/.local/share/gnome-shell/extensions/TaskBar@zpydr'
import-settings=true
position-tasks=4
date-menu-color='rgb(252,233,79)'
tasks-width=114
display-workspace-button=true
tasks-frame-color='rgb(239,41,41)'
active-task-background-color-set=true
system-menu-color='rgb(252,233,79)'
position-appview-button=3
display-label='both'
blink-tasks=true
display-desktop-button=true
overview=true
workspace-selector=true
display-tasks=true
appearance-selection='desktopbutton'
hover-event=0
top-panel=true
top-panel-original-background-color='rgba(0, 0, 0, 89)'
key-previous-task=['']
tasks-container-width-new=0
key-next-task=['']
display-tasks-label-color=true
position-desktop-button=1
active-task-background-color='rgb(46,52,54)'
appview-button-icon='/home/leslie/.local/share/gnome-shell/extensions/TaskBar@zpydr/images/appview-button-default.svg'


What I have done is install a default taskbar.dconf into the scripts folder.  This taskbar.dconf puts zpydr's TaskBar to the bottom centre, and adds some relocations.
By creating one zip file of TaskBar@zpydr, I have a default taskbar.dconf and the entire extension packaged together.
My next step is to make  a change to have   ~/taskbar.dconf   to ~/.taskbar.dconf  #(hidden file)

Regards 
 Leslie
 Leslie Satenstein
Montréal Québec, Canada

 

    On Tuesday, June 4, 2019, 3:25:55 a.m. GMT-4, lonix1 <notifications@github.com> wrote:  
 
 
IT WORKS AGAIN! 😄
 
For everyone else, he was referring to this line. After the edits, make sure to restart the gnome session - on ubuntu it's alt+f2 and then r.

Frankly I don't understand why this hack works, because it's just defining the object using the full namespace instead of importing it... but it works!

**Comment by joakimr-axis** [comment]
Update to fix the object.actor is deprecated warnings (followed by adding gnome-shell 3.36):
https://github.com/d97jro/gnome-shell-extension-taskbar/commit/a7f8eaba7d3c284255374c5aeec6bc38b06d60b5

**Comment by d97jro** [comment]
Fix object.actor is deprecated warnings: https://github.com/zpydr/gnome-shell-extension-taskbar/commit/73dd9784b985877aded6e55b324317024abde7b2 followed by adding gnome-shell 3.36: https://github.com/d97jro/gnome-shell-extension-taskbar/commit/a7f8eaba7d3c284255374c5aeec6bc38b06d60b5.
