### ISSUE TITLE
Taskbar icons disappear if a window that is not on the right edge is closed

### ISSUE THREAD

**Issue by kbailey4444** [zpydr/gnome-shell-extension-taskbar#56]
This is in gnome shell 3.14. If a window is closed and it is not rightmost in the taskbar, the icons to the right of that window's icon disappear.  Here is a video showing the bug. http://youtu.be/cjyIqsO86Mw

**Comment by skochxxl** [comment]
I had the same problem with 14.10 and also with 14.04. It is hard to reproduce because it only appears after some days of usage. I found a solution for it:

To debug this issue I started the gnome-shell from a terminal and when the issue occured I always gut an error like "app is null".

So I put in "extension.js" inside function "addTaskInList" after the first line ("let app = ... ") all the rest of this function in an IF clause

if (app)
{
.....
}

Hope it helps someone, for me it is fine now. I think it is safe to put this into production because it does not change anything but only catches if something is not as expected.
